[package]
name = "unitrait"
version = "2.0.0"
edition = "2024"
description = "Traits with a single global implementation, resolved at link time"
repository = "https://github.com/embassy-rs/unitrait"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = [
    "embedded",
    "no-std",
    "rust-patterns",
]

[dependencies]
unitrait-macros = { version = "2.0.0", path = "../unitrait-macros" }

[dev-dependencies]
trybuild = "1.0"
